name: "Deploy cloudformation stack to AWS"

on:
  push:
    branches: [ node18.x ]
  
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    
    steps:

      - name: "Checkout node18 branch"
        uses: actions/checkout@v3
        with:
          ref: node18.x
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: eu-north-1

      - name: Deploy VPC to AWS
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: deploy-vpc
          template: 00_foundation_layer.yaml
          no-fail-on-empty-changeset: "1"
                
      # - name: Deploy ECS to AWS
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: deploy-ecs
      #     template: 01_template_layer.yaml
      #     no-fail-on-empty-changeset: "1"
          
